version : "3.1"

services: 

  db:
    image: mysql
    env_file:
      - data.env
    environment: 
      - MYSQL_USER_ROOT=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projet-docker
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      restart: always
    ports:
      - '8000:80'
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    container_name: php_web
    ports: 
      - '8001:80'
    volumes:
      - ./app:/var/www/html
